version: '3'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'tg_bot_finished'
    ports:
      - 5434:5432
    environment:
      - 'POSTGRES_USER=aleshkey'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=tg_bot_db'